### ISSUE TITLE
AsyncHttpxClientWrapper has no attribute '_state' in v0.28.0

### ISSUE THREAD

**Issue by Kludex** [pydantic/httpx2#869]
> _Originally opened by [`@vintagedave`](https://github.com/vintagedave) on 2024-11-30 15:27:47 in [encode/httpx](https://github.com/encode/httpx/issues/3431)_

Hello. When I upgrade HTTPX from 0.27.0 to 0.28.0, I get the following error. I do not get a call stack, and I'm not expert enough on Python to know why (usually I would get one.)

This is likely being called by the openai library, which is version 1.50.2.

```
 File "/opt/venv/lib/python3.11/site-packages/httpx/_client.py", line 1984, in aclose

    if self._state != ClientState.CLOSED:

       ^^^^^^^^^^^

AttributeError: 'AsyncHttpxClientWrapper' object has no attribute '_state'
```

**Comment by Kludex** [comment]
> _Originally posted by [`@vfazio`](https://github.com/vfazio) on 2024-12-02T12:39:33Z_

you'll want to bump to at least https://github.com/openai/openai-python/releases/tag/v1.55.3 I think. older versions will not work will with httpx 0.28.0. you could optionally pin your httpx dependency to an older version.
